version: '3.8'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    restart: always
    depends_on:
      - db
    networks:
      - my-network
    command: ["dockerize", "-wait", "tcp://db:3306", "-timeout", "60s", "./main"]

  bff:
    build:
      context: ./bff
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    restart: always
    depends_on:
      - db
    networks:
      - my-network
    command: ["dockerize", "-wait", "tcp://db:3306", "-timeout", "60s", "python", "main.py"]

      
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: filip
      MYSQL_DATABASE: db
      MYSQL_PASSWORD: password
    ports:
      - 4450:3306
    volumes:
      - ./sql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - mysql-data:/var/lib/mysql
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  my-network:
    driver: bridge

volumes:
  mysql-data:
