swagger: '2.0'
info:
  title: Books Managing API
  description: API for managing books
  version: 1.0.0
tags:
  - name: Books
    description: The books managing API
paths:
  /books:
    get:
      summary: Lists all the books
      tags: 
        - Books
      responses:
        '200':
          description: Successful operation
        '400':
          description: Bad Request
            
    post:
      summary: Add a new book
      tags: 
        - Books
      parameters:
        - name: body
          in: body
          description: The book object
          required: true
          schema:
            $ref: '#/definitions/Books'
      responses:
        '201':
          description: The book was created
          schema:
            $ref: '#/definitions/Books'
        '500':
          description: Server error
  /books/{id}:
    get:
      summary: Get the book by ID
      tags: 
        - Books
      parameters:
        - name: id
          in: path
          description: ID of the book to return
          required: true
          type: string
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/Books'
        '400':
          description: Bad Request
    put:
      summary: Update the info of the book
      tags: 
        - Books
      parameters:
        - name: id
          in: path
          description: ID of the book to update
          required: true
          type: string
        - name: body
          in: body
          description: The book object
          required: true
          schema:
            $ref: '#/definitions/Books'
      responses:
        '200':
          description: Book updated successfully
          schema:
            $ref: '#/definitions/Books'
        '204':
          description: Success, no content
        '400':
          description: Bad Request
    delete:
      summary: Remove the book by ID
      tags: 
        - Books
      parameters:
        - name: id
          in: path
          description: ID of the book to delete
          required: true
          type: string
      responses:
        '204':
          description: Book deleted successfully
        '200':
          description: OK
        '400':
          description: Bad Request
definitions:
  Books:
    type: object
    required:
      - title
      - description
    properties:
      id:
        type: string
        description: The auto-generated ID of the book
      title:
        type: string
        description: The title of the book
      author:
        type: string
        description: The author's name
      description:
        type: string
        description: The book explanation
      status:
        type: string
        description: Available or borrowed
      newAddedBook:
        type: string
        format: date
        description: The date the book was added
