swagger: '2.0'
info:
  title: Books Managing API
  description: API for managing books
  version: 1.0.0
tags:
  - name: Books
    description: The books managing API
paths:
  /book:
    get:
      summary: Lists all the books
      tags: 
        - Books
      responses:
        '200':
          description: Get the main page
            
    post:
      summary:  Add a new book
      tags: 
        - Books
      parameters:
        - name: body
          in: body
          description: The book object
          required: true
          schema:
            $ref: '#/definitions/Books'
      responses:
        '200':
          description: The added book
          schema:
            $ref: '#/definitions/Books'
        '500':
          description: Some server error
  /book/{name}:
    get:
      summary: Get the book by ID
      tags: 
        - Books
      parameters:
        - name: name
          in: path
          description: ID of the book to return
          required: true
          type: string
      responses:
        '200':
          description: The book response by ID
  /book/{id}/info:      
    get:
      summary: Get the info of the book by ID
      tags: 
        - Books
      parameters:
        - name: id
          in: path
          description: ID of the book to return
          required: true
          type: string
      responses:
        '200':
          description: The book response by ID
          schema:
            $ref: '#/definitions/Books'
        # '404':k was not found  
    put:
      summary: Update the info of the book
      tags: 
        - Books
      parameters:
        - name: id
          in: path
          description: ID of the book to update
          required: true
          type: string
        - name: body
          in: body
          description: The book object
          required: true
          schema:
            $ref: '#/definitions/Books'
      responses:
        '200':
          description: The book was updated
          schema:
            $ref: '#/definitions/Books'
        '404':
          description: The book was not found
        '500':
          description: Some error happened
    delete:
      summary: Remove the book by ID
      tags: 
        - Books
      parameters:
        - name: id
          in: path
          description: ID of the book to delete
          required: true
          type: string
      responses:
        '200':
          description: The book was deleted
        '404':
          description: The book was not found
definitions:
  Books:
    type: object
    required:
      - title
      - description
      - finished
    properties:
      id:
        type: string
        description: The auto-generated ID of the book
      title:
        type: string
        description: The title of the book
      author:
        type: string
        description: The author's name
      description:
        type: string
        description: The book explanation
      status:
        type: string
        description: Available or borrowed
      createdBook:
        type: string
        format: date
        description: The date the book was added