openapi: 3.0.0
info:
  title: Library Management API
  description: API for managing a library's authors, books, subscribers, and borrowing system.
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /authors:
    get:
      summary: Get all authors
      responses:
        '200':
          description: A list of authors.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Author'
  /authorsbooks:
    get:
      summary: Get all authors and their books
      responses:
        '200':
          description: A list of authors with their books.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AuthorBook'
  /authors/{author_id}:
    get:
      summary: Get an author and their books by ID
      parameters:
        - in: path
          name: author_id
          required: true
          description: ID of the author to retrieve.
          schema:
            type: integer
      responses:
        '200':
          description: Details of the author and their books.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthorAndBooks'
  /books:
    post:
      summary: Add a new book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewBook'
      responses:
        '200':
          description: Book added successfully.
  /borrow:
    post:
      summary: Borrow a book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BorrowRequest'
      responses:
        '201':
          description: Book borrowed successfully.
  /return:
    post:
      summary: Return a borrowed book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReturnRequest'
      responses:
        '200':
          description: Book returned successfully.
  /subscribers_by_book:
    get:
      summary: Get subscribers who have borrowed a specific book
      parameters:
        - in: query
          name: book_id
          required: true
          description: ID of the book.
          schema:
            type: integer
      responses:
        '200':
          description: Subscribers who have borrowed the book.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Subscriber'
components:
  schemas:
    Author:
      type: object
      properties:
        id:
          type: integer
        lastname:
          type: string
        firstname:
          type: string
        photo:
          type: string
    AuthorBook:
      type: object
      properties:
        author_firstname:
          type: string
        author_lastname:
          type: string
        book_title:
          type: string
        book_photo:
          type: string
    AuthorAndBooks:
      type: object
      properties:
        author_firstname:
          type: string
        author_lastname:
          type: string
        author_photo:
          type: string
        books:
          type: array
          items:
            type: object
            properties:
              book_title:
                type: string
              book_photo:
                type: string
    NewBook:
      type: object
      properties:
        title:
          type: string
        author_id:
          type: integer
        photo:
          type: string
        details:
          type: string
    BorrowRequest:
      type: object
      properties:
        subscriber_id:
          type: integer
        book_id:
          type: integer
    ReturnRequest:
      type: object
      properties:
        subscriber_id:
          type: integer
        book_id:
          type: integer
    Subscriber:
      type: object
      properties:
        id:
          type: integer
        lastname:
          type: string
        firstname:
          type: string
        email:
          type: string
